title: Sourav Mangla
description: My Personal Blog
author: Sourav Mangla
logo: /static/img/avatar.png
github: https://github.com/ManglaSourav
about: Machine learning Enthusiast

baseurl: "https://ManglaSourav.github.io"
url: "https://ManglaSourav.github.io"

allowsearch: true

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \ManglaSourav
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
