title: Sourav Mangla
description: My Personal Blog
author: Sourav Mangla
logo: static/img/avatar.png
github:
about: Machine learning Enthusiast

# Author Settings
author: Sourav Mangla # add your name
author-img: avatar1.png # add your photo
about-author: I am a computer science engineer focusing on Machine Learning and Deep learning. # add description
social-twitter: manglasourav
social-facebook: # add your Facebook handle
social-github: manglasourav # add your Github handle
social-linkedin: sourav-mangla-617133129 # add your Linkedin handle
social-email: mangla.sourav96@gmail.com

# Disqus
discus-identifier: SouravMangla # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
