title: Hello, world! I'm Sourav Mangla
description: > # this means to ignore newlines until "baseurl:"
  This is my blog where I try to explain Machine Learning and Deep Learning topics.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Sourav Mangla # add your name
author-img: avatar1.png # add your photo
about-author: I am a computer science engineer focusing on Machine Learning and Deep learning. # add description
social-twitter: manglasourav
social-facebook: # add your Facebook handle
social-github: manglasourav # add your Github handle
social-linkedin: sourav-mangla-617133129 # add your Linkedin handle
social-email: mangla.sourav96@gmail.com

# Disqus
discus-identifier: sourav # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
